# MAIN base
baseURL = "https://pogoideapp.github.io/"
languageCode = "en-us"
title = "Pogoide | GO Notifications and Events"
theme = "apsho-hugo-theme"

[params]

# Header
logo = "images/appicontrans.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Get the latest app updates"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a> {year}"  

#contact
#email = "help@staticmania.com"
